version: '3'

services:
  jenkins:
    build: .
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins-ubuntu

volumes:
  jenkins_home:
